apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-producer
  name: java-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-producer
  template:
    metadata:
      labels:
        app: java-kafka-producer
    spec:
      containers:
      - name: java-kafka-producer
        image: mrabbah/java-kafka-producer:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: kafka-cluster-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef:
                name: java-kafka-producer
                key: user.crt
          - name: USER_KEY
            valueFrom:
              secretKeyRef:
                name: java-kafka-producer
                key: user.key
          - name: BOOTSTRAP_SERVERS
            value: kafka-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: my-topic
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-streams
  name: java-kafka-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-streams
  template:
    metadata:
      labels:
        app: java-kafka-streams
    spec:
      containers:
        - name: java-kafka-streams
          image: mrabbah/java-kafka-streams:latest
          env:
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: kafka-cluster-cluster-ca-cert
                  key: ca.crt
            - name: USER_CRT
              valueFrom:
                secretKeyRef:
                  name: java-kafka-streams
                  key: user.crt
            - name: USER_KEY
              valueFrom:
                secretKeyRef:
                  name: java-kafka-streams
                  key: user.key
            - name: BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap:9093
            - name: APPLICATION_ID
              value: java-kafka-streams
            - name: SOURCE_TOPIC
              value: my-topic
            - name: TARGET_TOPIC
              value: my-topic-reversed
            - name: LOG_LEVEL
              value: "INFO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-consumer
  name: java-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-consumer
  template:
    metadata:
      labels:
        app: java-kafka-consumer
    spec:
      containers:
      - name: java-kafka-consumer
        image: mrabbah/java-kafka-consumer:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: kafka-cluster-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef:
                name: java-kafka-consumer
                key: user.crt
          - name: USER_KEY
            valueFrom:
              secretKeyRef:
                name: java-kafka-consumer
                key: user.key
          - name: BOOTSTRAP_SERVERS
            value: kafka-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: my-topic-reversed
          - name: GROUP_ID
            value: java-kafka-consumer
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "10"
